version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 16
    pre_build:
        commands:
            - npm ci
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - rm -rf node_modules
artifacts:
    files:
        - '**/*'
    base-directory: build
