export const siteUrl = "https://dev.lumiastream.com";

export const socialPages = [
  {
    id: "developer-docs",
    route: "/docs/intro",
    title: "Lumia Stream Developer Docs",
    imageTitle: "Developer Docs",
    description: "Build integrations, overlays, plugins, alerts, and stream automation for Lumia Stream.",
    image: "developer-docs.png",
    code: ["REST API", "WebSockets", "Custom overlays", "Plugin SDK"],
  },
  {
    id: "mcp-server",
    route: "/docs/mcp/setup",
    title: "Lumia Stream MCP Server",
    imageTitle: "MCP Server",
    description:
      "Connect Claude, Cursor, Codex, VS Code, and other MCP clients to Lumia Stream for AI-assisted lights, alerts, chat, overlays, stream tools, and live state.",
    image: "mcp-server.png",
    code: ["get_state()", "send_command()", "send_tts()", "listen_for_events()"],
  },
  {
    id: "variables",
    route: "/docs/variables",
    title: "Variables & Templating",
    imageTitle: "Variables",
    description: "Use Lumia template variables and functions to render live stream data in chat, alerts, overlays, TTS, and commands.",
    image: "variables.png",
    code: ["{{username}}", "{{counter=deaths}}", "${sender}", "$(random.1-100)"],
  },
  {
    id: "chatbot-commands",
    route: "/docs/chatbot",
    title: "Chatbot Commands",
    imageTitle: "Chatbot Commands",
    description: "Create and customize Lumia chatbot commands for chat responses, moderation, games, TTS, lights, and stream actions.",
    image: "chatbot-commands.png",
    code: ["!commands", "!so @creator", "!permit viewer", "!roulette"],
  },
  {
    id: "overlays",
    route: "/docs/overlays",
    title: "Overlays",
    imageTitle: "Overlays",
    description: "Build stream overlays that react to Lumia variables, alerts, chat triggers, labels, goals, and live event data.",
    image: "overlays.png",
    code: ["Overlay.on('alert')", "labelPresets", "goalPresets", "chat triggers"],
  },
  {
    id: "alerts",
    route: "/docs/alerts/",
    title: "Alerts",
    imageTitle: "Alerts",
    description: "Explore every Lumia alert by platform, with payload examples and template variables for stream automation.",
    image: "alerts.png",
    code: ["twitch-subscriber", "youtube-superchat", "obs-scene-changed", "spotify-song-played"],
  },
  {
    id: "tts",
    route: "/docs/tts",
    title: "TTS",
    imageTitle: "TTS",
    description: "Trigger Lumia text-to-speech from alerts, chatbot commands, REST calls, WebSockets, custom code, and plugins.",
    image: "tts.png",
    code: ["send_tts", "voices", "expressive markup", "queue control"],
  },
  {
    id: "rest-api",
    route: "/docs/rest/clone-the-repo",
    title: "REST API",
    imageTitle: "REST API",
    description: "Control Lumia Stream from apps, games, and scripts with local HTTP endpoints for commands, alerts, colors, TTS, and overlays.",
    image: "rest-api.png",
    code: ["POST /api/send", "chat-command", "rgb-color", "studio-scene"],
  },
  {
    id: "websocket-api",
    route: "/docs/websockets/clone-the-repo",
    title: "WebSocket API",
    imageTitle: "WebSocket API",
    description: "Listen to live Lumia chat, alert, command, and stream-state events over WebSockets, or send API commands through the socket.",
    image: "websocket-api.png",
    code: ["ws://127.0.0.1:39231", "chat messages", "alerts", "state changes"],
  },
  {
    id: "custom-javascript",
    route: "/docs/custom-code/what-is-custom-javascript",
    title: "Custom JavaScript",
    imageTitle: "Custom JavaScript",
    description: "Extend Lumia Stream commands and alerts with JavaScript actions, helper functions, custom logic, and shared state.",
    image: "custom-javascript.png",
    code: ["run code actions", "helper functions", "global store", "custom scenarios"],
  },
  {
    id: "custom-overlays",
    route: "/docs/custom-overlays/custom-overlays-documentation",
    title: "Custom Overlays",
    imageTitle: "Custom Overlays",
    description: "Create custom Lumia browser-source overlays with JavaScript, typed overlay APIs, live events, and reusable examples.",
    image: "custom-overlays.png",
    code: ["Overlay class", "typed events", "browser source", "examples"],
  },
  {
    id: "plugin-sdk",
    route: "/docs/plugin-sdk/overview",
    title: "Plugin SDK",
    imageTitle: "Plugin SDK",
    description: "Build Lumia Stream marketplace plugins with manifests, settings, actions, events, overlays, TTS, lights, and integrations.",
    image: "plugin-sdk.png",
    code: ["manifest.json", "Plugin.onload()", "actions", "capabilities"],
  },
];

export function socialImageUrl(page) {
  return `${siteUrl}/img/social/${page.image}`;
}
